# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'MyVestiaireWeather' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyVestiaireWeather
  pod 'Alamofire', '~> 5.0.0-beta.5'

  target 'MyVestiaireWeatherTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
